### ISSUE TITLE
There is a problem to be solved

### ISSUE THREAD

**Issue by Halleyawoo** [nabsabraham/focal-tversky-unet#21]
Traceback (most recent call last):
  File "isic_train.py", line 93, in <module>
    model = newmodels.attn_reg(sgd, input_size, losses.focal_tversky)
  File "/media/nomachine/project/focal-tversky-unet-master/newmodels.py", line 241, in attn_reg
    img_input = Input(shape=input_size, name='input_scale1')
  File "/home/hfcui/.local/lib/python3.6/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/home/hfcui/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/hfcui/.local/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/home/hfcui/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 541, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by Halleyawoo** [comment]
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

is not worked

**Comment by Halleyawoo** [comment]
solved

**Comment by HudPesjan** [comment]
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> 
> is not worked

Hey, I'm having the same problem trying to figure out which version of Keras and TF with CUDA 10.0 to use to run this thing. Would you care to share your solution?
